/**
 * Generates an enterprise-ready, modular Playwright + TypeScript framework structure.
 * Follows the 2026 QA Automation Architecture Standards:
 * - Page Object Model (POM)
 * - Custom Fixtures (auth, apiClient, testData)
 * - Hybrid API + UI tests
 * - Cross-browser & parallel Playwright config
 * - GitHub Actions CI/CD pipeline
 * - HTML & Trace artifact reporting
 */

export function buildPlaywrightScaffold({
  testCases = [],
  targetUrl = 'https://example.com',
  options = {},
  aiGeneratedPom = '',
  aiGeneratedSpec = '',
  aiGeneratedApiSpec = '',
}) {
  const safeUrl = targetUrl.replace(/\/+$/, '');
  const projectName = options.projectName || 'forge-playwright-framework';
  const viewport = options.viewport || { width: 1280, height: 720 };
  const headless = options.headless !== false;

  // 1. Playwright Configuration File
  const playwrightConfig = `import { defineConfig, devices } from '@playwright/test';

/**
 * See https://playwright.dev/docs/test-configuration.
 * Production-ready Playwright config generated by ForgeQA.
 */
export default defineConfig({
  testDir: './tests',
  timeout: 45 * 1000,
  expect: {
    timeout: 8000,
  },
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 1,
  workers: process.env.CI ? 2 : undefined,
  reporter: [
    ['html', { outputFolder: 'playwright-report', open: 'never' }],
    ['list'],
    ['json', { outputFile: 'test-results/results.json' }],
  ],
  use: {
    baseURL: process.env.BASE_URL || '${safeUrl}',
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
    viewport: { width: ${viewport.width}, height: ${viewport.height} },
    headless: ${headless},
    actionTimeout: 15000,
    navigationTimeout: 30000,
    ignoreHTTPSErrors: true,
  },

  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },
    {
      name: 'Mobile Chrome',
      use: { ...devices['Pixel 5'] },
    },
  ],
});
`;

  // 2. package.json
  const packageJson = JSON.stringify(
    {
      name: projectName,
      version: '1.0.0',
      description: 'Production Playwright Automation Suite generated by ForgeQA',
      scripts: {
        test: 'playwright test',
        'test:headed': 'playwright test --headed',
        'test:ui': 'playwright test --ui',
        'test:debug': 'playwright test --debug',
        'test:smoke': 'playwright test --grep @smoke',
        'test:regression': 'playwright test --grep @regression',
        'test:api': 'playwright test tests/api',
        'test:e2e': 'playwright test tests/e2e',
        'test:chromium': 'playwright test --project=chromium',
        report: 'playwright show-report',
      },
      devDependencies: {
        '@playwright/test': '^1.49.0',
        '@types/node': '^20.0.0',
        typescript: '^5.0.0',
      },
    },
    null,
    2
  );

  // 3. tsconfig.json
  const tsconfigJson = JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module: 'NodeNext',
        moduleResolution: 'NodeNext',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
        baseUrl: '.',
        paths: {
          '@pages/*': ['./pages/*'],
          '@fixtures/*': ['./fixtures/*'],
          '@utils/*': ['./utils/*'],
        },
      },
      include: ['tests/**/*.ts', 'pages/**/*.ts', 'fixtures/**/*.ts', 'playwright.config.ts'],
    },
    null,
    2
  );

  // 4. Base Page Object
  const basePageCode = `import { Page, Locator, expect } from '@playwright/test';

/**
 * BasePage provides reusable interaction helpers, explicit wait wrappers,
 * and standard UI validation primitives across all Page Objects.
 */
export abstract class BasePage {
  readonly page: Page;

  constructor(page: Page) {
    this.page = page;
  }

  async goto(path: string = '/') {
    await this.page.goto(path, { waitUntil: 'domcontentloaded' });
  }

  async waitForPageReady() {
    await this.page.waitForLoadState('networkidle');
  }

  async captureScreenshot(name: string) {
    return await this.page.screenshot({
      path: \`test-results/screenshots/\${name}-\${Date.now()}.png\`,
      fullPage: true,
    });
  }

  async assertToastMessage(message: string | RegExp) {
    const toast = this.page.getByRole('status').or(this.page.getByRole('alert'));
    await expect(toast).toContainText(message);
  }
}
`;

  // 5. Default/AI Page Objects
  const pagesCode =
    aiGeneratedPom ||
    `import { Page, Locator, expect } from '@playwright/test';
import { BasePage } from './BasePage';

export class AppWorkflowPage extends BasePage {
  // Locators defined using user-facing Playwright role/text principles
  readonly mainHeading: Locator;
  readonly submitButton: Locator;
  readonly searchInput: Locator;
  readonly alertBanner: Locator;

  constructor(page: Page) {
    super(page);
    this.mainHeading = page.getByRole('heading', { level: 1 });
    this.submitButton = page.getByRole('button', { name: /(submit|confirm|continue|search)/i });
    this.searchInput = page.getByPlaceholder(/(search|filter|find)/i);
    this.alertBanner = page.getByRole('alert');
  }

  async performSearch(query: string) {
    await this.searchInput.fill(query);
    await this.searchInput.press('Enter');
  }

  async verifyHeadingVisible() {
    await expect(this.mainHeading).toBeVisible();
  }
}
`;

  // 6. Custom Fixtures (auth, testData, apiClient)
  const fixturesCode = `import { test as base, expect, APIRequestContext, request } from '@playwright/test';
import { AppWorkflowPage } from '../pages/AppPages';

type CustomFixtures = {
  workflowPage: AppWorkflowPage;
  apiClient: APIRequestContext;
  testData: {
    testRunId: string;
    sampleEmail: string;
    timestamp: number;
  };
};

export const test = base.extend<CustomFixtures>({
  // Pre-configured Page Object fixture
  workflowPage: async ({ page }, use) => {
    const workflow = new AppWorkflowPage(page);
    await use(workflow);
  },

  // Pre-configured API client fixture for hybrid API+UI test flows
  apiClient: async ({ baseURL }, use) => {
    const apiContext = await request.newContext({
      baseURL: baseURL || '${safeUrl}',
      extraHTTPHeaders: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
      },
    });
    await use(apiContext);
    await apiContext.dispose();
  },

  // Dynamic test data generator
  testData: async ({}, use) => {
    const timestamp = Date.now();
    await use({
      testRunId: \`run_\${timestamp}\`,
      sampleEmail: \`qa_test_\${timestamp}@forgeqa.local\`,
      timestamp,
    });
  },
});

export { expect };
`;

  // 7. E2E UI Spec
  const e2eSpecCode =
    aiGeneratedSpec ||
    `import { test, expect } from '../../fixtures/testFixtures';

test.describe('E2E Production Suite - ForgeQA Generated', () => {
  test.beforeEach(async ({ workflowPage }) => {
    await workflowPage.goto('/');
  });

${testCases
  .map(
    (tc, idx) => `  /**
   * ${tc.tcId}: ${tc.summary}
   * Category: ${tc.category || 'Functional'}
   * Steps: ${(tc.testSteps || []).join(' -> ')}
   */
  test('${tc.tcId} - ${tc.summary.replace(/'/g, "\\'")} @regression', async ({ workflowPage, page, testData }) => {
    // Step: Navigate & Verify page structure
    await workflowPage.verifyHeadingVisible();

    // Verify expected target outcomes
    await expect(page).toHaveURL(new RegExp('.*'));
  });`
  )
  .join('\n\n')}
});
`;

  // 8. Full-Stack Hybrid API Spec
  const apiSpecCode =
    aiGeneratedApiSpec ||
    `import { test, expect } from '../../fixtures/testFixtures';

test.describe('Hybrid API + Backend State Validation Suite', () => {
  test('API: Healthcheck & Service Status Validation @api @smoke', async ({ apiClient }) => {
    const response = await apiClient.get('/api/health').catch(async () => {
      // Fallback if /api/health does not exist
      return await apiClient.get('/');
    });
    expect([200, 204, 301, 302]).toContain(response.status());
  });

  test('Hybrid: API Data Seeding -> UI Validation Chain @api @regression', async ({ apiClient, workflowPage, testData }) => {
    // 1. API Step: Seed test payload or verify session token
    // const seedRes = await apiClient.post('/api/items', { data: { name: testData.sampleEmail } });
    // expect(seedRes.ok()).toBeTruthy();

    // 2. UI Step: Validate seeded entity renders in browser
    await workflowPage.goto('/');
    await expect(workflowPage.page).toBeDefined();
  });
});
`;

  // 9. GitHub Actions CI/CD Pipeline
  const githubWorkflow = `name: Playwright Tests CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 2 * * *' # Nightly regression run at 02:00 UTC
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Test suite tag to run'
        required: true
        default: '@smoke'
        type: choice
        options:
          - '@smoke'
          - '@regression'
          - '@api'
          - 'all'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2]
        shardTotal: [2]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests (Sharded Matrix)
        run: |
          if [ "\${{ github.event.inputs.test_suite }}" == "all" ] || [ -z "\${{ github.event.inputs.test_suite }}" ]; then
            npx playwright test --shard=\${{ matrix.shardIndex }}/\${{ matrix.shardTotal }}
          else
            npx playwright test --grep "\${{ github.event.inputs.test_suite }}" --shard=\${{ matrix.shardIndex }}/\${{ matrix.shardTotal }}
          fi
        env:
          CI: 'true'
          BASE_URL: \${{ secrets.TEST_BASE_URL || '${safeUrl}' }}

      - name: Upload Playwright Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-shard-\${{ matrix.shardIndex }}
          path: playwright-report/
          retention-days: 14

      - name: Upload Test Traces & Videos on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-shard-\${{ matrix.shardIndex }}
          path: test-results/
          retention-days: 7
`;

  // 10. README.md
  const readmeMd = `# ${projectName}

> Production-style Playwright + TypeScript Test Automation Framework generated with **ForgeQA**.

---

## 📁 Architecture Overview

\`\`\`
├── .github/
│   └── workflows/
│       └── playwright.yml         # Matrix CI/CD pipeline with sharding & artifacts
├── pages/
│   ├── BasePage.ts                # Interaction helpers & assertion wrappers
│   └── AppPages.ts                # Page Object Models using role-based locators
├── fixtures/
│   └── testFixtures.ts            # Extended test fixtures (POM, apiClient, testData)
├── tests/
│   ├── e2e/
│   │   └── workflow.spec.ts       # End-to-end UI regression tests
│   └── api/
│       └── api-fullstack.spec.ts  # Hybrid API + UI chaining & contract tests
├── playwright.config.ts           # Cross-browser & reporting configuration
├── package.json                   # Dependencies & npm run scripts
└── tsconfig.json                  # TypeScript compiler options
\`\`\`

---

## 🚀 Getting Started

### 1. Install Dependencies
\`\`\`bash
npm install
npx playwright install --with-deps
\`\`\`

### 2. Run Tests
\`\`\`bash
# Run all tests headlessly
npm test

# Run tests in interactive UI mode (Time-travel debugging)
npm run test:ui

# Run only Smoke tests
npm run test:smoke

# Run only Hybrid API tests
npm run test:api

# Run on specific browser
npm run test:chromium
\`\`\`

### 3. View Reports & Traces
\`\`\`bash
npm run report
\`\`\`

---

## 🛡️ Best Practices Included
- **Page Object Model (POM)**: Decoupled selectors from test specs for maximum maintainability.
- **Resilient Locators**: Built using Playwright's user-facing priority locators (\`getByRole\`, \`getByPlaceholder\`, \`getByTestId\`).
- **Hybrid API Testing**: Uses Playwright \`request\` context for fast setup & data teardown.
- **Artifact Diagnostics**: Automatic traces, failure screenshots, and videos collected in \`test-results/\`.
`;

  return [
    { path: 'playwright.config.ts', content: playwrightConfig, language: 'typescript' },
    { path: 'package.json', content: packageJson, language: 'json' },
    { path: 'tsconfig.json', content: tsconfigJson, language: 'json' },
    { path: 'pages/BasePage.ts', content: basePageCode, language: 'typescript' },
    { path: 'pages/AppPages.ts', content: pagesCode, language: 'typescript' },
    { path: 'fixtures/testFixtures.ts', content: fixturesCode, language: 'typescript' },
    { path: 'tests/e2e/workflow.spec.ts', content: e2eSpecCode, language: 'typescript' },
    { path: 'tests/api/api-fullstack.spec.ts', content: apiSpecCode, language: 'typescript' },
    { path: '.github/workflows/playwright.yml', content: githubWorkflow, language: 'yaml' },
    { path: 'README.md', content: readmeMd, language: 'markdown' },
  ];
}

export function buildCypressScaffold({
  testCases = [],
  targetUrl = 'https://example.com',
  options = {},
  language = 'typescript',
  aiGeneratedPom = '',
  aiGeneratedSpec = '',
  aiGeneratedApiSpec = '',
}) {
  const safeUrl = targetUrl.replace(/\/+$/, '');
  const isTs = language !== 'javascript';
  const ext = isTs ? 'ts' : 'js';

  const cypressConfig = isTs
    ? `import { defineConfig } from 'cypress';

export default defineConfig({
  e2e: {
    baseUrl: '${safeUrl}',
    viewportWidth: ${options.viewport?.width || 1280},
    viewportHeight: ${options.viewport?.height || 720},
    video: false,
    screenshotOnRunFailure: true,
  },
});`
    : `const { defineConfig } = require('cypress');

module.exports = defineConfig({
  e2e: {
    baseUrl: '${safeUrl}',
    viewportWidth: ${options.viewport?.width || 1280},
    viewportHeight: ${options.viewport?.height || 720},
    video: false,
  },
});`;

  const packageJson = JSON.stringify(
    {
      name: options.projectName || 'forge-cypress-framework',
      version: '1.0.0',
      description: 'Enterprise Cypress Test Automation Framework generated by ForgeQA',
      scripts: {
        test: 'cypress run',
        'test:headed': 'cypress run --headed',
        'test:open': 'cypress open',
      },
      devDependencies: {
        cypress: '^13.7.0',
        ...(isTs ? { typescript: '^5.0.0', '@types/node': '^20.0.0' } : {}),
      },
    },
    null,
    2
  );

  const basePageCode = `export class BasePage {
  visit(path = '/') {
    cy.visit(path);
  }

  waitForPageLoad() {
    cy.document().should('have.property', 'readyState', 'complete');
  }

  getElement(selector) {
    return cy.get(selector);
  }
}`;

  const pagesCode =
    aiGeneratedPom ||
    `import { BasePage } from './BasePage';

export class AppPages extends BasePage {
  submitButton() {
    return cy.get('button[type="submit"], [role="button"]');
  }

  performAction() {
    this.visit('/');
  }
}`;

  const supportE2e = `// Cypress E2E Support File
import './commands';

beforeEach(() => {
  // Global test setup
});`;

  const supportCommands = `// Custom Cypress commands
Cypress.Commands.add('login', () => {
  cy.log('User login initiated');
});`;

  const e2eSpecCode =
    aiGeneratedSpec ||
    `import { AppPages } from '../pages/AppPages';

describe('Enterprise Cypress E2E Suite', () => {
  const app = new AppPages();

  beforeEach(() => {
    app.visit('/');
  });

${testCases
  .map(
    (tc) => `  it('${tc.tcId}: ${tc.summary}', () => {
    // Expected: ${tc.expected || 'Success'}
    cy.url().should('include', '${safeUrl}');
  });`
  )
  .join('\n\n')}
});`;

  const apiSpecCode =
    aiGeneratedApiSpec ||
    `describe('Cypress Hybrid API Health Suite', () => {
  it('Verifies endpoint response status', () => {
    cy.request({
      url: '${safeUrl}',
      failOnStatusCode: false,
    }).then((response) => {
      expect(response.status).to.be.oneOf([200, 201, 301, 302, 404]);
    });
  });
});`;

  const githubWorkflow = `# GitHub Actions CI/CD for ForgeQA Cypress
name: ForgeQA Cypress Automated Testing

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          browser: chrome
`;

  const readmeMd = `# ForgeQA Cypress Test Automation Framework

Generated enterprise-grade Cypress testing suite.

## Running Tests
\`\`\`bash
npm install
npm test
npm run test:open
\`\`\`
`;

  return [
    {
      path: `cypress.config.${ext}`,
      content: cypressConfig,
      language: isTs ? 'typescript' : 'javascript',
    },
    { path: 'package.json', content: packageJson, language: 'json' },
    ...(isTs
      ? [
          {
            path: 'tsconfig.json',
            content: JSON.stringify(
              {
                compilerOptions: {
                  target: 'ES2022',
                  module: 'CommonJS',
                  strict: true,
                  types: ['cypress'],
                },
              },
              null,
              2
            ),
            language: 'json',
          },
        ]
      : []),
    {
      path: `cypress/pages/BasePage.${ext}`,
      content: basePageCode,
      language: isTs ? 'typescript' : 'javascript',
    },
    {
      path: `cypress/pages/AppPages.${ext}`,
      content: pagesCode,
      language: isTs ? 'typescript' : 'javascript',
    },
    {
      path: `cypress/support/e2e.${ext}`,
      content: supportE2e,
      language: isTs ? 'typescript' : 'javascript',
    },
    {
      path: `cypress/support/commands.${ext}`,
      content: supportCommands,
      language: isTs ? 'typescript' : 'javascript',
    },
    {
      path: `cypress/e2e/workflow.cy.${ext}`,
      content: e2eSpecCode,
      language: isTs ? 'typescript' : 'javascript',
    },
    {
      path: `cypress/e2e/api-fullstack.cy.${ext}`,
      content: apiSpecCode,
      language: isTs ? 'typescript' : 'javascript',
    },
    { path: '.github/workflows/cypress.yml', content: githubWorkflow, language: 'yaml' },
    { path: 'README.md', content: readmeMd, language: 'markdown' },
  ];
}

export function buildSeleniumScaffold({
  testCases = [],
  targetUrl = 'https://example.com',
  options = {},
  language = 'typescript',
  aiGeneratedPom = '',
  aiGeneratedSpec = '',
  aiGeneratedApiSpec = '',
}) {
  const safeUrl = targetUrl.replace(/\/+$/, '');
  const normLang = language.toLowerCase();

  if (normLang === 'python') {
    const conftestPy = `import pytest
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

@pytest.fixture
def driver():
    chrome_options = Options()
    if ${options.headless !== false ? 'True' : 'False'}:
        chrome_options.add_argument("--headless=new")
    chrome_options.add_argument("--window-size=${options.viewport?.width || 1280},${options.viewport?.height || 720}")
    driver = webdriver.Chrome(options=chrome_options)
    driver.implicitly_wait(10)
    yield driver
    driver.quit()
`;

    const requirementsTxt = `pytest>=8.0.0
selenium>=4.18.0
pytest-html>=4.1.0
requests>=2.31.0
`;

    const pytestIni = `[pytest]
testpaths = tests
addopts = -v --html=report.html --self-contained-html
`;

    const basePagePy = `from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class BasePage:
    def __init__(self, driver):
        self.driver = driver
        self.wait = WebDriverWait(driver, 10)

    def navigate(self, path=""):
        self.driver.get(f"${safeUrl}{path}")

    def find(self, locator):
        return self.wait.until(EC.visibility_of_element_located(locator))

    def click(self, locator):
        self.wait.until(EC.element_to_be_clickable(locator)).click()
`;

    const appPagesPy =
      aiGeneratedPom ||
      `from selenium.webdriver.common.by import By
from pages.base_page import BasePage

class AppPages(BasePage):
    SUBMIT_BTN = (By.CSS_SELECTOR, "button[type='submit']")

    def perform_action(self):
        self.navigate("/")
`;

    const workflowPy =
      aiGeneratedSpec ||
      `from pages.app_pages import AppPages

class TestWorkflow:
${testCases
  .map(
    (tc) => `    def test_${tc.tcId.toLowerCase().replace(/[^a-z0-9_]/g, '_')}(self, driver):
        """${tc.summary}"""
        page = AppPages(driver)
        page.navigate("/")
        assert driver.current_url.startswith("http")
`
  )
  .join('\n')}
`;

    const apiTestPy =
      aiGeneratedApiSpec ||
      `import requests

def test_api_health():
    res = requests.get("${safeUrl}")
    assert res.status_code in [200, 201, 301, 302, 404]
`;

    const githubWorkflow = `# GitHub Actions CI/CD for Selenium Python
name: ForgeQA Selenium Python CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest
`;

    const readmeMd = `# ForgeQA Selenium Python Framework

Enterprise pytest + Selenium WebDriver automation framework.

## Running Tests
\`\`\`bash
pip install -r requirements.txt
pytest
\`\`\`
`;

    return [
      { path: 'conftest.py', content: conftestPy, language: 'python' },
      { path: 'pytest.ini', content: pytestIni, language: 'ini' },
      { path: 'requirements.txt', content: requirementsTxt, language: 'text' },
      { path: 'pages/base_page.py', content: basePagePy, language: 'python' },
      { path: 'pages/app_pages.py', content: appPagesPy, language: 'python' },
      { path: 'tests/test_workflow.py', content: workflowPy, language: 'python' },
      { path: 'tests/test_api_health.py', content: apiTestPy, language: 'python' },
      { path: '.github/workflows/selenium-python.yml', content: githubWorkflow, language: 'yaml' },
      { path: 'README.md', content: readmeMd, language: 'markdown' },
    ];
  }

  if (normLang === 'java') {
    const pomXml = `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.forgeqa</groupId>
    <artifactId>selenium-automation</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.18.1</version>
        </dependency>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.9.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>`;

    const basePageJava = `package pages;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.ui.WebDriverWait;
import java.time.Duration;

public abstract class BasePage {
    protected WebDriver driver;
    protected WebDriverWait wait;

    public BasePage(WebDriver driver) {
        this.driver = driver;
        this.wait = new WebDriverWait(driver, Duration.ofSeconds(10));
    }

    public void navigate(String path) {
        driver.get("${safeUrl}" + path);
    }
}`;

    const appPagesJava =
      aiGeneratedPom ||
      `package pages;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

public class AppPages extends BasePage {
    public AppPages(WebDriver driver) {
        super(driver);
    }

    public void performAction() {
        navigate("/");
    }
}`;

    const testJava =
      aiGeneratedSpec ||
      `package tests;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.testng.Assert;
import org.testng.annotations.*;
import pages.AppPages;

public class WorkflowTest {
    private WebDriver driver;

    @BeforeMethod
    public void setup() {
        ChromeOptions options = new ChromeOptions();
        ${options.headless !== false ? 'options.addArguments("--headless=new");' : ''}
        driver = new ChromeDriver(options);
    }

${testCases
  .map(
    (tc, i) => `    @Test
    public void test_${tc.tcId.toLowerCase().replace(/[^a-z0-9_]/g, '_')}() {
        AppPages app = new AppPages(driver);
        app.performAction();
        Assert.assertTrue(driver.getCurrentUrl().startsWith("http"));
    }`
  )
  .join('\n\n')}

    @AfterMethod
    public void teardown() {
        if (driver != null) driver.quit();
    }
}`;

    const testngXml = `<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="ForgeQA Selenium Suite">
    <test name="E2E Tests">
        <classes>
            <class name="tests.WorkflowTest"/>
        </classes>
    </test>
</suite>`;

    return [
      { path: 'pom.xml', content: pomXml, language: 'xml' },
      { path: 'src/main/java/pages/BasePage.java', content: basePageJava, language: 'java' },
      { path: 'src/main/java/pages/AppPages.java', content: appPagesJava, language: 'java' },
      { path: 'src/test/java/tests/WorkflowTest.java', content: testJava, language: 'java' },
      { path: 'testng.xml', content: testngXml, language: 'xml' },
      {
        path: '.github/workflows/selenium-java.yml',
        content: `# Java Selenium CI\nname: Java Selenium CI\non: [push]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-java@v4\n        with:\n          java-version: '17'\n          distribution: 'temurin'\n      - run: mvn test`,
        language: 'yaml',
      },
      {
        path: 'README.md',
        content: `# ForgeQA Selenium Java Framework\n\nRun \`mvn test\` to execute.`,
        language: 'markdown',
      },
    ];
  }

  // TypeScript / JavaScript Selenium scaffold
  const isTs = normLang !== 'javascript';
  const ext = isTs ? 'ts' : 'js';

  const seleniumConfig = `// Selenium WebDriver Configuration
export const config = {
  baseUrl: '${safeUrl}',
  viewport: { width: ${options.viewport?.width || 1280}, height: ${options.viewport?.height || 720} },
  headless: ${options.headless !== false},
};`;

  const packageJson = JSON.stringify(
    {
      name: options.projectName || 'forge-selenium-framework',
      version: '1.0.0',
      scripts: {
        test: 'mocha --timeout 40000 tests/**/*.spec.ts',
      },
      devDependencies: {
        selenium_webdriver: '^4.18.0',
        mocha: '^10.3.0',
        ...(isTs
          ? {
              typescript: '^5.0.0',
              '@types/node': '^20.0.0',
              '@types/mocha': '^10.0.0',
              'ts-node': '^10.9.0',
            }
          : {}),
      },
    },
    null,
    2
  );

  const basePageCode = `import { WebDriver, By, until } from 'selenium-webdriver';

export abstract class BasePage {
  constructor(protected driver: WebDriver) {}

  async navigate(path = '/') {
    await this.driver.get(\`${safeUrl}\${path}\`);
  }

  async waitForElement(locator: By) {
    return await this.driver.wait(until.elementLocated(locator), 10000);
  }
}`;

  const pagesCode =
    aiGeneratedPom ||
    `import { By } from 'selenium-webdriver';
import { BasePage } from './BasePage';

export class AppPages extends BasePage {
  async submit() {
    const btn = await this.waitForElement(By.css('button[type="submit"]'));
    await btn.click();
  }
}`;

  const specCode =
    aiGeneratedSpec ||
    `import { Builder, WebDriver } from 'selenium-webdriver';
import { AppPages } from '../pages/AppPages';

describe('Selenium E2E Test Suite', function () {
  let driver: WebDriver;
  let app: AppPages;

  before(async function () {
    driver = await new Builder().forBrowser('chrome').build();
    app = new AppPages(driver);
  });

  after(async function () {
    if (driver) await driver.quit();
  });

${testCases
  .map(
    (tc) => `  it('${tc.tcId}: ${tc.summary}', async function () {
    await app.navigate('/');
  });`
  )
  .join('\n\n')}
});`;

  return [
    {
      path: `selenium.config.${ext}`,
      content: seleniumConfig,
      language: isTs ? 'typescript' : 'javascript',
    },
    { path: 'package.json', content: packageJson, language: 'json' },
    ...(isTs
      ? [
          {
            path: 'tsconfig.json',
            content: JSON.stringify(
              { compilerOptions: { target: 'ES2022', module: 'CommonJS', strict: true } },
              null,
              2
            ),
            language: 'json',
          },
        ]
      : []),
    {
      path: `pages/BasePage.${ext}`,
      content: basePageCode,
      language: isTs ? 'typescript' : 'javascript',
    },
    {
      path: `pages/AppPages.${ext}`,
      content: pagesCode,
      language: isTs ? 'typescript' : 'javascript',
    },
    {
      path: `tests/e2e/workflow.spec.${ext}`,
      content: specCode,
      language: isTs ? 'typescript' : 'javascript',
    },
    {
      path: '.github/workflows/selenium.yml',
      content: `# Selenium CI\nname: Selenium CI\non: [push]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - run: npm ci && npm test`,
      language: 'yaml',
    },
    {
      path: 'README.md',
      content: `# ForgeQA Selenium Framework\n\nRun \`npm test\` to execute.`,
      language: 'markdown',
    },
  ];
}

export function buildPuppeteerScaffold({
  testCases = [],
  targetUrl = 'https://example.com',
  options = {},
  language = 'typescript',
  aiGeneratedPom = '',
  aiGeneratedSpec = '',
  aiGeneratedApiSpec = '',
}) {
  const safeUrl = targetUrl.replace(/\/+$/, '');
  const isTs = language !== 'javascript';
  const ext = isTs ? 'ts' : 'js';

  const packageJson = JSON.stringify(
    {
      name: options.projectName || 'forge-puppeteer-framework',
      version: '1.0.0',
      scripts: {
        test: 'jest --runInBand',
      },
      devDependencies: {
        puppeteer: '^22.4.0',
        jest: '^29.7.0',
        ...(isTs
          ? {
              typescript: '^5.0.0',
              '@types/node': '^20.0.0',
              '@types/jest': '^29.5.0',
              'ts-jest': '^29.1.0',
            }
          : {}),
      },
    },
    null,
    2
  );

  const basePageCode = `import type { Page } from 'puppeteer';

export abstract class BasePage {
  constructor(protected page: Page) {}

  async navigate(path = '/') {
    await this.page.goto(\`${safeUrl}\${path}\`, { waitUntil: 'domcontentloaded' });
  }
}`;

  const pagesCode =
    aiGeneratedPom ||
    `import { BasePage } from './BasePage';

export class AppPages extends BasePage {
  async clickSubmit() {
    await this.page.click('button[type="submit"]');
  }
}`;

  const specCode =
    aiGeneratedSpec ||
    `import puppeteer, { Browser, Page } from 'puppeteer';
import { AppPages } from '../pages/AppPages';

describe('Puppeteer Test Suite', () => {
  let browser: Browser;
  let page: Page;
  let app: AppPages;

  beforeAll(async () => {
    browser = await puppeteer.launch({ headless: ${options.headless !== false ? 'true' : 'false'} });
    page = await browser.newPage();
    app = new AppPages(page);
  });

  afterAll(async () => {
    if (browser) await browser.close();
  });

${testCases
  .map(
    (tc) => `  test('${tc.tcId}: ${tc.summary}', async () => {
    await app.navigate('/');
    expect(page.url()).toContain('http');
  });`
  )
  .join('\n\n')}
});`;

  return [
    { path: 'package.json', content: packageJson, language: 'json' },
    ...(isTs
      ? [
          {
            path: 'tsconfig.json',
            content: JSON.stringify(
              { compilerOptions: { target: 'ES2022', module: 'CommonJS', strict: true } },
              null,
              2
            ),
            language: 'json',
          },
        ]
      : []),
    {
      path: `pages/BasePage.${ext}`,
      content: basePageCode,
      language: isTs ? 'typescript' : 'javascript',
    },
    {
      path: `pages/AppPages.${ext}`,
      content: pagesCode,
      language: isTs ? 'typescript' : 'javascript',
    },
    {
      path: `tests/e2e/workflow.test.${ext}`,
      content: specCode,
      language: isTs ? 'typescript' : 'javascript',
    },
    {
      path: '.github/workflows/puppeteer.yml',
      content: `# Puppeteer CI\nname: Puppeteer CI\non: [push]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - run: npm ci && npm test`,
      language: 'yaml',
    },
    {
      path: 'README.md',
      content: `# ForgeQA Puppeteer Framework\n\nRun \`npm test\` to execute.`,
      language: 'markdown',
    },
  ];
}

export function buildFrameworkScaffold({
  framework = 'playwright',
  language = 'typescript',
  testCases = [],
  targetUrl = 'https://example.com',
  options = {},
  aiGeneratedPom = '',
  aiGeneratedSpec = '',
  aiGeneratedApiSpec = '',
}) {
  const normFw = (framework || 'playwright').toLowerCase();
  const normLang = (language || 'typescript').toLowerCase();

  switch (normFw) {
    case 'cypress':
      return buildCypressScaffold({
        testCases,
        targetUrl,
        options,
        language: normLang,
        aiGeneratedPom,
        aiGeneratedSpec,
        aiGeneratedApiSpec,
      });
    case 'selenium':
      return buildSeleniumScaffold({
        testCases,
        targetUrl,
        options,
        language: normLang,
        aiGeneratedPom,
        aiGeneratedSpec,
        aiGeneratedApiSpec,
      });
    case 'puppeteer':
      return buildPuppeteerScaffold({
        testCases,
        targetUrl,
        options,
        language: normLang,
        aiGeneratedPom,
        aiGeneratedSpec,
        aiGeneratedApiSpec,
      });
    case 'playwright':
    default:
      return buildPlaywrightScaffold({
        testCases,
        targetUrl,
        options,
        language: normLang,
        aiGeneratedPom,
        aiGeneratedSpec,
        aiGeneratedApiSpec,
      });
  }
}
