// Comprehensive disposable / temporary email domain blocklist
// Source: aggregated from multiple public blocklists
const DISPOSABLE_DOMAINS = new Set([
  "0-mail.com", "027168.com", "10-minute.net",   "10-minuten-mail.de",
  "10minut.com.pl", "10minutemail.cf", "10minutemail.co.uk", "10minutemail.com",
  "10minutes-mail.com", "1ce.us", "1chuan.com", "1usemail.com",
  "2chome.net", "2prong.com", "3trt6bq.com", "4gfdsgfd.com",
  "4mail.cf", "4mail.ga", "4mail.gq", "4warding.com",
  "4warding.net", "4warding.org", "5jukj77d.com", "5mail.cf",
  "5mail.ga", "5mail.gq", "6ipus3g.com", "6mail.cf",
  "6mail.ga", "6mail.gq", "7mail.cf", "7mail.ga",
  "7mail.gq", "8mail.cf", "8mail.ga", "8mail.gq",
  "9mail.cf", "9mail.ga", "9mail.gq", "a-bc.net",
  "abyssemail.com", "abyssmail.com", "afrobacon.com", "air2token.com",
  "ajacied.com", "ama-trade.de", "amail.com", "amilegit.com",
  "animail.net", "anonymail.org", "anonymousemail.me", "anonymousness.com",
  "anthony-junkmail.com", "anymail.org", "apkmd.com",
  "appc.se", "appinventors.nl", "armyspy.com", "arurgitu.gq",
  "at0mik.org", "auti.st", "autoprocessor.net", "awbeta.net",
  "axcept.net", "azazazatashkent.tk", "azcomputerworks.com", "azmeil.tk",
  "baconporker.com", "badoop.com", "badhus.org", "banit.club",
  "basscode.org", "bastore-openshop.ga", "bazaar.com", "bbetweenr.com",
  "bcaoo.com", "beaverbait.com", "bearsarefuzzy.com", "bedava-mail.com",
  "belljonestax.com", "benipaula.org", "bertshoes.com", "best-day.pw",
  "betr.co", "bitymails.us", "bko.kiev.ua", "blogmyway.org",
  "bluebottle.com", "bnote.com", "bofthew.com", "bongobongo.cf",
  "bongobongo.ga", "bongobongo.gq", "bonobo.email", "bookthemmore.com",
  "bootybay.de", "boun.cr", "bouncemail.de", "bouncr.com",
  "box-imao.com", "boxformail.com", "brandbuzz.vip", "brauckhoff.xyz",
  "breakthru.com", "brefmail.com", "brennendesreich.de", "broadbandninja.com",
  "bsnow.net", "buffemail.com", "bugmenot.com", "buonafede.tech",
  "burnthespam.info", "busymail.com", "busymail.net", "busymail.org",
  "buyusedlibrarybooks.org", "buzzcompact.com", "c2.hu", "c3email.xyz",
  "cachedot.net", "caisel.com", "callzones.com", "candymail.de",
  "caramail.com", "cartelera.org", "caseedu.com", "casualdx.com",
  "cekajahhs.xyz", "cellurl.com", "centermail.com", "centermail.net",
  "chammy.info", "cheaphub.net", "cheatmail.de", "chibetv.com",
  "chielo.com", "chilkat.com", "chumpstakingdumps.com", "cigarconnect.com",
  "civx.org", "ck12j5v.com", "cl-cl.org", "clandest.in",
  "clarkgriswald.net", "clearmail.online", "clipmail.eu", "clrmail.com",
  "cmail.club", "cmail.com", "cnn.com", "cobarekyo.xyz",
  "cock.li", "cocodani.com", "codeandscotch.com", "codivide.com",
  "coieo.com", "coldemail.info", "compareshippingrates.org", "comwest.de",
  "conf.xyz", "cool.fr.nf", "coolandwacky.us", "coolimpool.org",
  "correo.blogos.net", "cosmorph.com", "courriel.fr.nf", "courrieltemporaire.com",
  "crankmails.com", "crapmail.org", "crazymailing.com",
  "cross-law.com", "crossedguid.com", "crotslep.com", "crotslep.email",
  "cubiclink.com", "cuemail.com", "curryworld.de", "cx.de-a.xyz",
  "cyber-innovation.club", "cyber-phone.eu", "dacoolest.com", "dammexe.net",
  "damnthespam.com", "dandikmail.com", "dazzling.best", "deagot.com",
  "dealja.com", "deekayen.us", "defomail.com", "degradedfun.net",
  "delayload.com", "delayload.net", "delikkt.de", "demen.ml",
  "demislhd.com", "dengekiburst.ga", "der-kombi.de", "derkombi.de",
  "derluxuswagen.de", "desvirtuais.online", "dev-null.cf", "dev-null.ga",
  "dev-null.gq", "dev-null.ml", "dextm.ro", "dfgggg.org",
  "diapaulpainting.com", "dicksinhisan.us", "dicksnisan.com", "digitalsanctuary.com",
  "dildovs.com", "dileberate.com", "dildoshrdere.online", "dingdao.at",
  "dinkmail.com", "discard.email", "discardmail.com", "discardmail.de",
  "dispo.in", "dispomail.eu", "disposable-mail.com", "disposable.cf",
  "disposable.ga", "disposable.gq", "disposable.ml", "disposableaddress.com",
  "disposableemailaddresses.com", "disposableemailaddresses.emailmiser.com", "disposableinbox.com",
  "dispose.it", "disposeamail.com", "disposemail.com", "dispostable.com",
  "divermail.com", "dlemail.com", "dmtc.edu.pl", "dnses.ro",
  "doanart.com", "dobson.in", "docmail.com", "dodgeit.com",
  "dodgit.com", "dodgit.org", "doiea.com", "dolphinnet.net",
  "domainaing.cf", "domainaing.ga", "domainaing.gq", "domainaing.ml",
  "domforfb1.tk", "domforfb2.tk", "domforfb3.tk", "domforfb4.tk",
  "domforfb5.tk", "domforfb6.tk", "domforfb7.tk", "domforfb8.tk",
  "domforfb9.tk", "domozmail.com", "donemail.ru", "dontreg.com",
  "dontsendmespam.de", "doramail.com", "drdrb.com", "dred.ru",
  "dremixd.com", "drivetagdev.com", "droolingfanboy.de", "dropcake.net",
  "drope.ml", "dropmail.me", "dsiay.com", "dspark.net",
  "dubsoft.net", "duck2.club", "dudmail.com", "dump-email.info",
  "dumpandjunk.com", "dumpmail.com", "dumpmail.de", "dumpyemail.com",
  "dupin.info", "duskmail.com", "dx.abuser.eu", "dx.allowed.org",
  "dx.ez.lv", "dx.sly.io", "e-mail.com", "e-mail.net",
  "e-mail.org", "e-postkasten.com", "e-postkasten.de", "e-postkasten.eu",
  "e3z.de", "easytrashmail.com", "ebeschlussbuch.de",
  "ecolo-online.fr", "edgex.ru", "edv.to", "ee2.pl",
  "efo.kr", "efxs.ca", "eight12.com", "eintagsmail.de",
  "elitevipatlantamodels.com", "email-fake.cf", "email-fake.com",
  "email-fake.ga", "email-fake.gq", "email-fake.ml", "email-jetable.fr",
  "email-jetable.xyz", "email-temp.com", "email.cbes.net", "email.net",
  "email.tk", "email45.com", "emailage.cf", "emailage.ga",
  "emailage.gq", "emailage.ml", "emailate.com", "emaildiscard.com",
  "emaildrop.io", "emailfake.ml", "emailfreedom.ml", "emailgo.de",
  "emailias.com", "emailigo.de", "emailinfive.com", "emailisvalid.com",
  "emaillime.com", "emailmenow.net", "emailmiser.com", "emailna.co",
  "emailn.de", "emailnator.com", "emailo.pro", "emailondeck.com",
  "emailportal.org", "emailproxsy.com", "emails.ga", "emailsensei.com",
  "emailsingularity.net", "emailspam.cf", "emailspam.ga", "emailspam.gq",
  "emailspam.ml", "emailsy.info", "emailtech.info", "emailtemporanea.com",
  "emailtemporanea.net", "emailtemporar.ro", "emailtemporario.com.br",
  "emailthe.net", "emailtmp.com", "emailto.de", "emailwarden.com",
  "emailx.at", "emailx.net", "emailxfer.com", "emailz.cf",
  "emailz.ga", "emailz.gq", "emailz.ml", "emeil.in",
  "emeil.ir", "emil.com", "emka.hu", "emkei.cf",
  "emkei.ga", "emkei.gq", "emkei.ml", "emlhub.com",
  "emlpro.com", "emltmp.com", "empireanime.ga", "enayu.com",
  "enron.com", "entertainmentmail.com", "ephemeral.email", "ericmail.com",
  "eripo.net", "esbanoo.ru", "escanmail.com", "esiix.com",
  "esprity.com", "etgdev.de", "ether123.net", "ethereum1.org",
  "ethersports.org", "etlgr.com", "evopo.com", "example.com",
  "exbte.com", "explodemail.com", "express.net.ua", "ezgy2s.com",
  "ezlo.co", "ezprice.net", "f4k.es", "facebook-email.cf",
  "facebook-email.ga", "facebook-email.gq", "facebook-email.ml",
  "facebookmail.gq", "facebookmail.ml", "fag.wf", "failinga.nl",
  "faithkills.com", "fake-box.com", "fake-email.pp.ua", "fake-mail.cf",
  "fake-mail.ga", "fake-mail.gq", "fake-mail.ml", "fake.i.ng",
  "fakemail.com", "fakemail.net", "fakemailgenerator.net",
  "fakemailgenerator.com", "fammix.com", "fanclub.pm", "fangoh.com",
  "fansworldwide.de", "fantasymail.de", "fastacura.com", "fastchevy.com",
  "fastchrysler.com", "fastemails.us", "fastkawasaki.com", "fastmazda.com",
  "fastmitsubishi.com", "fastnissan.com", "fastsubaru.com", "fastsuzuki.com",
  "fasttoyota.com", "fastyamaha.com", "fatflap.com", "fdg5gh7jh.com",
  "fdfdsfds.com", "fightallspam.com", "figjs.com", "fiifke.de",
  "filzmail.com", "fivemail.de", "fixmail.tk", "fizmail.com",
  "fleckens.hu", "flemail.ru", "flurred.com", "flyspam.com",
  "fmailx.tk", "fnord.me", "foobarbot.net", "footard.com",
  "forecastertests.com", "forgetmail.com", "fornow.eu", "forward.cat",
  "fprog.de", "free-email.cf", "free-email.ga", "free-email.gq",
  "freebabysittercam.com", "freeblackbootytube.com", "freecat.net",
  "freemail.tweakly.net", "freemail.ms", "freemails.cf", "freemails.ga",
  "freemails.gq", "freemails.ml", "freemtpa.org", "freeplumpervideos.com",
  "freeschoolgirlvids.com", "freeshemaledvds.com", "freesistercam.com",
  "freeteenbums.com", "freundin.ru", "friendlymail.co.uk", "friscaa.com",
  "fristsub.com", "frogmail.com", "from.onmypc.info", "fromru.com",
  "frostbyte.tk", "fs5tg0.com", "fs-fet0.xyz", "fuckingduh.com",
  "fuckme69.club", "fucknmemail.com", "fuckrog.com", "fudgerub.com",
  "fuirio.com", "fukaru.com", "fux0rdu2.com", "fxnxs.com",
  "fyii.de", "g7i3e.cf", "g7i3e.ga", "g7i3e.gq",
  "g7i3e.ml", "gaggle.net", "galaxy.tv", "gally.jp",
  "gamail.com", "gamecastlive.com", "gamerdon.com", "gamil.com",
  "gamil.net", "garage46.com", "garrymccooey.com", "gastrointestinalife.com",
  "gav0.com", "gaygeek.us", "gaylc.com", "gazeta.pl",
  "gazzetta.com", "geekforex.com", "geew.ru", "gen.uu.gl",
  "geniu.su", "gentoss.im", "get-mail.cf", "get-mail.ga",
  "get-mail.gq", "get-mail.ml", "get.pp.ua", "get1mail.com",
  "get2mail.com", "getairmail.com", "getamailbox.com", "getapet.net",
  "getcoolmail.info", "getfun.men", "getmails.eu", "getnada.com",
  "getnowmail.com", "getonemail.com", "getonemail.net", "gishpuppy.com",
  "givememail.club", "glitch.sx", "globaltouron.com", "glubex.com",
  "glyqj.com", "gmai.com", "goatmail.org", "goemailgo.com",
  "golemico.com", "gomail.in", "googlegroups.com", "gorillaswithdirtyarmpits.com",
  "gotmail.com", "gotmail.net", "gotmail.org", "gowikibooks.com",
  "gowikicampus.com", "gowikicars.com", "gowikifilms.com", "gowikigames.com",
  "gowikimusic.com", "gowikinetwork.com", "gowikitravel.com", "gowikitv.com",
  "grandmamail.com", "grandmasmail.com", "great-host.in", "greensloth.com",
  "greggamel.com", "greggamel.net", "gregorygamel.com", "gregorygamel.net",
  "grish.de", "growlcombine.com", "grr.la", "gsrv.co.uk",
  "guerillamail.biz", "guerillamail.com", "guerillamail.net", "guerillamail.org",
  "guerrillamail.biz", "guerrillamail.com", "guerrillamail.de", "guerrillamail.net",
  "guerrillamail.org", "guerrillamailblock.com", "gufum.com", "gustr.com",
  "gynzi.com", "gynzyte.com", "h8s.org", "habitue.net",
  "hackermail.com", "hackersquad.com", "hackrz.xyz", "hahawrong.com",
  "halofarm.com", "haltospam.com", "hamsun.dev", "happymail.guru",
  "happysinner.co.uk", "harakirimail.com", "hartbot.de", "hasanmail.ml",
  "hatespam.org", "hawrong.com", "haydoo.com", "hazelnutspatch.com",
  "hbo.com", "hccmail.com", "hellodjy.tk", "hellomail.net",
  "helpinghandtax.center", "herp.in", "heypiggy.com", "hidemail.de",
  "hidemail.pro", "hidemail.us", "hideweb.xyz", "higgins.is.very.mail",
  "highbarn.com", "hiltonvr.com", "hmail.us", "hmamail.com",
  "hochsitze.com", "holl.xyz", "hollisholland.nl", "hollywoodmassage.com",
  "hometown.yahoo.com", "homail.com", "honeysuckle.com", "hopemail.biz",
  "hornyalwary.com", "hostcalls.com", "hostguru.info", "hostlaba.com",
  "hot-mail.cf", "hot-mail.ga", "hot-mail.gq", "hot-mail.ml",
  "hotmai.com",   "hotmail.co", "hotpop.com", "hotpop3.com",
  "huangniu8.com", "hukkmu.tk", "hulapla.de", "humaility.com",
  "hugotp.com",
  "hvastudies.eu", "hwsye.net", "ibm.com",
  "icantbelieveineedtoexplainthissh.it", "icemail.club", "ichigo.me",
  "icx.in", "icx.ro", "ieatspam.eu", "ieatspam.info",
  "ieh-mail.de", "ige.es", "ignoremail.com", "ihateyoualot.info",
  "ijustdontcare.com", "ikbenspamvrij.nl", "ilikespam.com", "imails.info",
  "imap.cc", "imstations.com", "inaby.com", "iname.com",
  "inbax.tk", "inbound.plus", "inbox.si", "inboxalias.com",
  "inboxclean.com", "inboxclean.org", "inboxed.pw", "inboxhub.net",
  "inboxkitten.com", "inboxproxy.com", "inclusiveprogress.com", "incognitomail.com",
  "incognitomail.net", "incognitomail.org", "indeedlebeans.com", "infocom.zp.ua",
  "inggo.org", "inoutmail.com", "inoutmail.eu", "inoutmail.info",
  "inoutmail.net", "insanumingeniumhomebrew.com", "insorg-mail.info", "instakash.net",
  "instant-mail.de", "instantblingmail.info", "instantemailaddress.com",
  "instantmail.fr", "internetbiz.com", "internetmailing.info", "internode.com",
  "investore.co", "iowa.com", "ip6.li", "ipdoor.com",
  "ipfighter.org", "ipiranga.dynu.com", "ipoo.org", "ippandansei.tk",
  "ipsur.net", "irabops.com", "irish2me.com", "iroid.com",
  "ironiebehindert.de", "irr.kr", "isdaq.com", "isosq.com",
  "istii.ro", "isukrainestillacountry.com", "it7.ovh", "itcompu.com",
  "itplace.ovh", "iuemail.ml", "iwi.net", "ixx.io",
  "j3rqt89ez.com", "jajxz.com", "jakfctqj.xyz", "janproz.com",
  "jcr2l.com", "jdmadventures.com", "jeeemail.com", "jellowo.com",
  "jenterysys.com", "jet-lander.com", "jetable.com", "jetable.fr.nf",
  "jetable.net", "jetable.org", "jetable.pp.ua", "jilossesq.com",
  "jmail.com", "jmail.ovh", "job4u.company", "jobbikszine.com",
  "jobs-to-be-done.net", "joelonsoftware.com", "johansenassociates.net",
  "jourrapide.com", "jp.ftp.sh", "jungkamushukum.com", "junk.yourcomic.com",
  "junk1e.com", "junkmail.com", "junkmail.net", "junkmail.org",
  "junkmail.guide", "jxhxms.xyz", "kademen.com", "kadokawa.cf",
  "kadokawa.ga", "kadokawa.gq", "kadokawa.ml", "kaffeeschluerfer.com",
  "kanci.cf", "kanci.ga", "kanci.gq", "kanci.ml",
  "kanker.website", "kaper.com", "kappcha.com", "karrtino.com",
  "kasmail.com", "kaspop.com", "katztube.com", "kazelink.ml",
  "kbox.li", "keepmymail.com", "keinhirn.de", "keipino.de",
  "kekita.com", "kennedy808.com", "kiani.com", "king-yosef.de",
  "kir.ch.tc", "kirasjera.tk", "kisstwink.com", "kitnastar.com",
  "kiwibox.com", "klassmaster.com", "klassmaster.net", "kler.xyz",
  "klick-tipp.us", "klipschx12.com", "kloap.com", "kludgemush.com",
  "kmaill.com", "kommunity.biz", "kook.ml", "kopagas.com",
  "kopaka.net", "kosmetik-obenaus.de", "kostenlosmail.com", "koszmail.pl",
  "kravecoffeebar.com", "krdsw.com", "krovatka.shop", "krypton.tk",
  "kuhrap.com", "kulturbetrieb.info", "kurzepost.de", "kvhrr.com",
  "kvhrs.com", "kvhrw.com", "kzbrown.com", "l33r.eu",
  "l7b2l.com", "labetteraverouge.at", "lacedmail.com", "lackmail.net",
  "lackmail.ru", "lagiapan.online", "lakngin.com", "lakora.us",
  "lalala.fyi", "landmail.co", "laoeq.com", "last-chance.pro",
  "lastmail.co", "lastmail.com", "latemails.com", "lavabit.com",
  "lawlita.com", "lazyinbox.com", "lazyinbox.us", "ldop.com",
  "leap2020.eu", "lee.mailspam.xyz", "leeching.net", "leforte.com",
  "legalrc.loan", "lemonad.email", "letmeinonthis.com", "letthemeatspam.com",
  "lexisense.com", "liamcyrus.com", "lifebyfood.com", "lifetimefriends.info",
  "link2mail.net", "linkedintuts2016.pw", "litedrop.com", "lkrjio.xyz",
  "loadby.com", "loan101.pro", "loansmatter.com", "loaoa.com",
  "lol.com", "lolfreak.net", "lolmail.ga", "lolmail.tk",
  "lookugly.com", "lopl.co.cc", "lordsofts.com", "lortemail.dk",
  "loseyourip.com", "louhl.com", "loveme.not-loving-you.com", "loveyou.xyz",
  "lovesea.gq", "lpfmgmtltd.com", "lr7.us", "lroid.com",
  "lrvot.com", "lubieczytac.pl", "luckymail.org", "lukecarriere.com",
  "lukemail.info", "lukop.dk", "luv2.us", "lyfestylecredits.com",
  "lyricx.net", "m21.cc", "m4ilweb.info", "ma1l.biz",
  "mafiaspam.com", "magechain.shop", "magicmail.ml", "magspam.net",
  "maibaumer.net", "mail-8.cn", "mail-app.net", "mail-c.tk",
  "mail-ecology.com", "mail-filter.com", "mail-owl.com", "mail-share.com",
  "mail-temp.com", "mail-temporaire.com", "mail-temporaire.fr",
  "mail.a3s.li", "mail.aws910.com", "mail.backflip.org", "mail.bccto.com",
  "mail.bentrask.com", "mail.bestoption25.club", "mail.by", "mail.card动机.com",
  "mail.china.com", "mail.co.za",
  "mail.germanywest.hu", "mail.gu", "mail.gen.tr", "mail.mezimages.net",
  "mail.misterpinball.com", "mail.nu", "mail.pandora.com", "mail.rpzr.xyz",
  "mail.sisna.com", "mail.spacewar.com", "mail.svenz.eu",
  "mail.thegreatcomputer.com", "mail.tonut.org", "mail.wtf", "mail.za.com",
  "mail0.ga", "mail1a.de", "mail1st.com", "mail21.cc",
  "mail2rss.org", "mail2tor.com", "mail3.xyz", "mail4you.ml",
  "mail4trash.com", "mail333.com", "mail666.ru", "mail707.com",
  "mail72.com", "mail8.ga", "mailback.com", "mailbidon.com",
  "mailbiz.biz", "mailblocks.com", "mailbox52.ga", "mailbox80.biz",
  "mailbox82.biz", "mailbox87.de", "mailbox92.biz", "mailbucket.org",
  "mailcat.biz", "mailcatch.com", "mailchoose.co", "mailcker.com",
  "mailcuk.com", "mailde.de", "mailde.info", "maildrop.cc",
  "maildrop.cf", "maildrop.ga", "maildrop.gq", "maildrop.ml",
  "maildu.de", "maildx.com", "maileater.com", "mailed.in",
  "mailed.ro", "maileimer.de", "mailexpire.com", "mailf5.com",
  "mailfa.tk", "mailfall.com", "mailforspam.com", "mailfree.ga",
  "mailfree.gq", "mailfree.ml", "mailfreeonline.com", "mailfs.com",
  "mailguard.me", "mailgutter.com", "mailhazard.com", "mailhazard.us",
  "mailhero.io", "mailhex.com", "mailhub.pro", "mailhz.me",
  "mailimate.com", "mailin8r.com", "mailinatar.com", "mailinater.com",
  "mailinator.co.uk", "mailinator.com", "mailinator.gq", "mailinator.info",
  "mailinator.net", "mailinator.org", "mailinator.us", "mailinator.xyz",
  "mailinator2.com", "mailinatorzz.mooo.com", "mailinea.com", "mailismagic.com",
  "mailita.tk", "mailjunk.net", "mailjunk.org", "mailjuice.space",
  "mailmate.com", "mailme.gq", "mailme.lv", "mailme24.com",
  "mailmetrash.com", "mailmoat.com", "mailmoth.com", "mailms.com",
  "mailnator.com", "mailnesia.com", "mailnull.com", "mailo.com",
  "mailonaut.com", "mailorc.com", "mailorg.org", "mailox.fun",
  "mailpick.biz", "mailpooch.com", "mailpost.net", "mailpride.com",
  "mailproxsy.com", "mailquack.com", "mailr24.com", "mailrocket.biz",
  "mailscrap.com", "mailservices.xyz", "mailshiv.com", "mailshrine.com",
  "mailsingpost.com", "mailsiphon.com", "mailslapping.com", "mailslite.com",
  "mailsmurf.com", "mailspam.xyz", "mailspamtest.com", "mailsteward.com",
  "mailstorm.pw", "mailsuck.org", "mailsx.com", "mailtemp.info",
  "mailtemp.net", "mailtemporaire.com", "mailtemporaire.fr",
  "mailtome.de", "mailtothis.com", "mailtrash.net", "mailtrix.net",
  "mailtv.net", "mailtv.tv", "mailtzu.com", "mailu.ml",
  "mailuniverse.com", "mailvalley.com", "mailview.org", "mailvust.com",
  "mailware.xyz", "mailwastro.com", "mailworks.org", "mailzi.ru",
  "mailzilla.com", "mailzilla.org", "mainerfolg.info", "makemenaughty.club",
  "makromusic.com", "malayalamdtp.com", "malove.site", "mama3.org",
  "mandraghen.cf", "manifestgenerator.com", "manna.us", "manybrain.com",
  "marcemac.com", "marco69.org", "marfer.org", "margerycarlson.com",
  "mariela186.xyz", "mariushub.net", "marshlimited.net", "martin.xyz",
  "martu86.com", "masas.lol", "massacretorture.com", "massani.com",
  "masterofwarcraft.net", "mastires.com", "matamuasu.cf", "matchpol.online",
  "materiali.ml", "maxown.com", "mbe.kr", "mbx.cc",
  "mcache.net", "mdhc.tk", "meantinc.com", "mebelnu.info",
  "mechanicalresumes.com", "medsheet.com", "meepsheep.eu", "mehome.com",
  "meinspamschutz.de", "meltmail.com", "mephistore.co", "merry.pink",
  "messagebees.de", "messwiththebestdielikethe.rest", "mezimages.net", "mfsa.info",
  "mfsa.ru", "mhzayt.online", "miaferrari.com", "midcoastcustoms.com",
  "midcoastcustoms.net", "midlertidig.com", "midlertidig.net", "midlertidig.org",
  "mierdamail.com", "migmail.net", "migmail.pl", "migumail.com",
  "mihep.com", "mijnhva.nl", "mikalove.com", "milapost.com",
  "militarymail.com", "millol.com", "mim.ovh", "mindless.com",
  "minds.com", "minecraftrabbit.com", "minecraftralph.com", "mini-mail.net",
  "minimail.gq", "minmail.tk", "minsmail.com", "mintemail.com",
  "misterpinball.com", "misu.gq", "mjf.gq", "mjukglass.nu",
  "moburl.com", "mobz.org", "mok19.com", "monachat.tk",
  "moncourrier.fr.nf", "monemail.fr.nf", "mongoloid.wiki", "monmail.fr.nf",
  "monumentmail.com", "moojunk.com", "moonwake.com", "moreawesomethanyou.com",
  "moreorcs.com", "motorcyclemonkeys.com", "mountainregion.info", "mox.pp.ua",
  "moy-e-mail.ru", "mozillafirefox.com", "msgden.com", "msgnr.com",
  "mshotmail.com", "msftmail.com", "msgos.com", "mspeciosa.com",
  "mswork.ru", "msxd.com", "mt2009.com", "mt2020.com",
  "mtmdev.com", "muathegame.com", "muchomail.com", "mucxy.xyz",
  "mufux.com", "mugglenet.org", "mujmail.cz", "mullerheiss.com",
  "multiply.cloud", "mundodigital.me", "mundomail.net", "munoubengoshi.gq",
  "mupload.nl", "musify.ru", "muttvorld.com", "mvrht.com",
  "mvrht.net", "my-card.net", "my-pomsies.com", "my-teddyy.com",
  "my10minutemail.com", "mybitti.de", "mycleaninbox.net", "mycorner-mail.net",
  "myemailman.com", "myfreeserver.com", "mygeoweb.com", "myindohome.services",
  "myinterserver.ml", "mykita.com", "mymail-in.net", "mymail90.com",
  "mymailoasis.com", "mymaily.lottery", "mynet.com", "myopang.com",
  "mypacks.net", "mypartyclip.de", "myphantomemail.com", "mysamp.de",
  "myspaceinc.com", "myspaceinc.net", "myspaceinc.org", "myspacepimpedup.com",
  "myspamless.com", "mytemp.email", "mytempemail.com", "mytempmail.com",
  "mytrashmail.com", "mywarnernet.net", "myway.com", "myxabay.com",
  "n1nja.org", "n2r.com", "n8.gs", "nada.email",
  "nada.ltd", "nafko.cf", "nakedtruth.biz", "nanonym.ch",
  "nas.er.us", "nationalguardian.com", "nationalspeedway.com", "naturalious.com",
  "nbox.notif.me", "nctuiem.xyz", "neben.de", "neibu.ml",
  "nekolove.ru", "nemui.com", "neomailbox.com", "nepwk.com",
  "nervmich.net", "nervtmich.net", "net.ua", "netcom.com",
  "netmails.com", "netmails.net", "netricity.nl", "netris.net",
  "netviewer-france.com", "netzidiot.de", "nevermail.de", "neverbox.com",
  "neverbox.net", "neverbox.org", "newbpotato.tk", "newideasfornewpeople.info",
  "newmail.com", "newsmag.us", "next.ovh", "nextmail.in",
  "nextmail.info", "nextstopvalhalla.com", "nezdiro.org", "nezzart.com",
  "nfast.net", "nguyenusedcars.com", "nh3.ro", "nicebush.com",
  "nicegarden.info", "nicknassar.com", "nincsmail.com", "nincsmail.hu",
  "nikeaz.com", "nmail.cf", "nnh.com", "nnot.net",
  "no-spam.ws", "no-ux.com", "noblepioneer.com", "nobugmail.com",
  "nobulk.com", "nobuma.com", "noclickemail.com", "node.net",
  "nodie.online", "noicd.com", "nokiamail.com", "nolemail.ga",
  "nom.za", "nomail.cf", "nomail.ga", "nomail.gq",
  "nomail.ml", "nomail.net", "nomail.pw", "nomail.xl.cx",
  "nomorespamemails.com", "nongnuea.com", "nono.net", "nonspam.eu",
  "nonspam.de", "noref.fr", "norih.com", "norseforce.com",
  "northenmotorscooters.com", "nospam.win", "nospam.email-4u.net", "nospam.ze.tc",
  "nospam4.us", "nospamfor.us", "nothankyou.com", "nothingtoseehere.ca",
  "notmail.com", "notmail.net", "notmail.org", "notrnailinator.com",
  "notsharingmy.info", "nowhere.org", "nowmymail.com", "ntlhelp.net",
  "nubescontrol.com", "null.net", "nunom.com", "nurgsmail.com",
  "nut.cc", "nutpa.net", "nuts2u.com", "nwldx.com",
  "nwytg.net", "nwytg.netmail", "o2.pl", "oaktreeinvestmentsllc.com",
  "oath.com", "objectmail.com", "obobbo.com", "obxpestcontrol.com",
  "odnorazovoe.ru", "oepia.com", "oerpub.org", "office-email.com",
  "offsetmail.com", "offshorecontrol.info", "ofsc.ru", "oftalmologos.net",
  "ohhmymail.com", "oida.icu", "oihyoi.com", "oilant.com",
  "okclprojects.com", "okrenttwt.tk", "olivestree.com", "olympianetwork.net",
  "omail.pro", "omnievents.org", "one-mail.com", "one2mail.info",
  "oneoffmail.com", "onewaymail.com", "onmail.win", "onmailzone.com",
  "online.ms", "onlyyouandme.xyz", "onmail.win", "onqin.com",
  "ontyne.biz", "oolus.com", "oopi.org", "opayq.com",
  "openmailbox.com", "opentrash.com", "opmmail.com", "oppojob.com",
  "optician.com", "orango.xyz", "ordinaryamerican.net", "orthodontist.net",
  "outlawspam.com", "outlookch.com", "outlookpro.net", "outpesch.com",
  "ov3u841.com", "ovi.usa.cc", "ovimail.com", "ovlov.cf",
  "ovlov.ga", "ovlov.gq", "ovlov.ml", "owlpic.com",
  "oxfarm1.com", "oxopoha.com", "ozost.com", "ozu.es",
  "p71ce1m.com", "pagamenti.tk", "paharpurmim.ga", "pakadebu.ga",
  "paller.cf", "paller.gq", "pancakemail.com", "pandorabox.info",
  "panix.com", "paplease.com", "parasite.shop", "parisannonce.com",
  "parsimail.com", "pastebitch.com", "paulfucksallthebitches.com", "pavilionx.com",
  "pay-mon.com", "pc152.space", "pcass.com", "pcpostal.com",
  "pecinan.com", "pecinan.net", "pecinan.org", "penisgoes.in",
  "penoto.tk", "pepbot.com", "pepsi.com", "peterdethier.com",
  "petrolstation.com", "petrzilka.net", "pfui.ru", "pharmasiana.com",
  "phimcanz.com", "photomark.net", "phpbb.uu.gl", "phuksie.gq",
  "picknamer.com", "pimpedupmyspace.com", "pinehill-seattle.org", "pingir.com",
  "pink-party.info", "pinnaclemortgage.co", "pip.i.ng", "pipni.cz",
  "pitaniezdorovie.com", "pizzajunk.com", "pkmail.com", "placemailon.com",
  "pleasure-points.com", "plexolan.de", "pluno.com", "plus.com",
  "plw.me", "pobox.hu", "pobox.sk", "pocitacova-pomoc.sk",
  "podam.pl", "podmailer.com", "poehali.buzz", "poiuy.xyz",
  "pokemail.net", "pokerslots.com", "polacy-dungannon.tk", "polarkingxx.ml",
  "politikerclub.de", "polyfaust.com", "polynomial.email", "pojok.ml",
  "ponp.xyz", "pookmail.com", "poopiebutt.club", "pop3.com",
  "pop3.net", "pop3.org", "popmail.com", "popmail.net",
  "popsmail.com", "porkbun.com", "pornmail.com", "porsh.net",
  "post.com", "post.xyz", "post1.xyz", "postaccesslite.com",
  "postcardsfromukraine.xyz", "postfach.cc", "postfach2go.de", "posthav.com",
  "postmail.com", "postonline.me", "poutine.xyz", "powered.name",
  "powerencry.com", "ppc-russia.com", "ppetw.com", "prayersa3.com",
  "premios.ml", "pride.naquadria.com", "primabananen.net", "primat.es",
  "prime-gators.ru", "printers.ovh", "privacy.net", "privatdemail.net",
  "privy-mail.com", "privy-mail.de", "privymail.de", "pro-tag.org",
  "probioscorner.com", "prodigy.net", "profast.top", "programming.ky",
  "promail.com", "promail.ovh", "promails.xyz", "promiedos.com.ar",
  "prontomail.com", "protestant.com", "prowhatnow.com",
  "psh.me", "psyg.com", "ptmail.top", "ptoqs.com",
  "puffsucks.com", "pukabox.com", "pumperkinnie.com", "punggur.cf",
  "pungtur.ga", "puppetmail.de", "puriag.com", "purplemail.com",
  "put2.net", "puttanamaiala.tk", "putthisinyourspamdatabase.com", "pw.epac.to",
  "pw-mail.cf", "pw-mail.ga", "pw-mail.gq", "pw-mail.ml",
  "pwp.lv", "pyx.ovh", "q7z6t.com", "qasti.com",
  "qbfree.us", "qc.to", "qibl.at", "qip.ru",
  "qisdo.com", "qisoa.com", "qmal.com", "qoika.com",
  "qoz.net", "qs.dp76.com", "qs.gy",
  "qsl.ro", "qt1.net", "quadrafit.com", "quick-mail.info",
  "quickemail.info", "quickinbox.com", "quickmail.nl", "quid4.com",
  "ququb.com", "qvy.me", "qwertymail.com", "qwickmail.com",
  "r8.one", "r9y9nw.com", "raffles.tech", "raetp9.com",
  "rainbowly.ml", "raketenmail.de", "rancidhome.net", "ranmako.com",
  "rantelon.xyz", "rao.kr", "rbb.org", "rcpt.at",
  "rdctv.ml", "rdklcrv.xyz", "re-gister.com", "realitytrain.org",
  "reallymymail.com", "realtyagent.pro", "rebates.stream", "receiveee.com",
  "receiveee.net", "recipeforfailure.com", "recode.me", "recursor.net",
  "recyclemail.dk", "recycledmail.com", "recycledmail.net", "recycledmail.org",
  "redchan.it", "reddit.usa.cc", "reddithub.com", "redfeathercrow.com",
  "redmail.xyz", "redpen.trade", "redwhale.xyz", "refine.xyz",
  "regbypass.com", "regbypass.comsafe-mail.net", "rejectmail.com", "reliable-mail.com",
  "remail.cf", "remail.ga", "remail.gq", "remarkable.rocks",
  "remote.li", "reptilegenetics.com", "resgedupfed.gq", "resmail.net",
  "resolvenow.xyz", "retromail.site", "revolvingdoorhoax.com", "rhyta.com",
  "richmondheights.com", "rickymail.com", "rinsemail.com", "rma.ec",
  "rmqkr.net", "rnailinator.com", "ro.lt", "robertspcrepair.com",
  "rollindo.agency", "ronnierage.net", "rootfest.net", "rotaniliam.com",
  "rover.info", "roxxmail.com", "rppkn.com", "rr-1.xyz",
  "rr-2.xyz", "rr-3.xyz", "rr-4.xyz", "rr-5.xyz",
  "rtrtr.com", "rts6k.xyz", "rudymail.ml", "runi.ca",
  "rupamail.com", "rupamail.net", "rupamail.org", "rustydoor.com",
  "rvb.ro", "s0ny.net", "s1x1.xyz", "s33db0x.com",
  "sabrestaff.com", "sackboii.com", "safe-mail.net", "safemail.pro",
  "safetymail.info", "safetypost.de", "saharanightstempe.com", "salmeow.tk",
  "saltysushi.com", "samsclass.info", "sandelf.de", "sandwhichvideo.com",
  "sanfinder.com", "sanim.net", "sanstr.com", "sast.ro",
  "saturn2020.com", "sausen.com", "saynotospams.com", "scafolding.com",
  "scanova.io", "scatmail.com", "schachrol.com", "schafmail.de",
  "schmeissweg.tk", "schrott-email.de", "sd3.in", "secmail.pw",
  "secretemail.de", "secure-mail.biz", "secure-mail.cc", "secured-link.net",
  "seekapps.com", "seekjobs4u.com", "seemail.xyz", "selfdestructingmail.com",
  "selfdestructingmail.org", "send22u.info", "sendfree.org", "sendingspecialflyers.com",
  "sendspam.org", "sendtomyemail.xyz", "sent.as", "sent.at",
  "sent.com", "sentinelbrowsers.com", "sentry-mail.com", "serga.com.ar",
  "servemymail.com", "server.ms", "sesmail.com", "sexboxx.net",
  "sexxstories.eu", "sezet.com", "shalar.net", "sharedmailbox.org",
  "sharkbait.me", "sharkslasers.com", "sheryde.com", "shhmooze.com",
  "shhuut.org", "shieldedmail.com", "shieldemail.com", "shiftmail.com",
  "shipfromto.com", "shiphappens.com", "shirleystemplecovers.com", "shitaway.cf",
  "shitaway.ga", "shitaway.gq", "shitaway.ml", "shitmail.de",
  "shitmail.me", "shitmail.org", "shittymail.de", "shittymail.org",
  "shmeriously.com", "shootmail.com", "shortmail.net", "shotmail.ru",
  "showslow.de", "shrib.com", "shut.name", "shut.ws",
  "sialk.xyz", "sify.com", "sikomo.info", "siliwangi.ga",
  "silvercoin.life", "simail.xyz", "simexchange.xyz", "simsmail.com",
  "sin.cl", "sinnlos-mail.de", "sinnlos.info", "siteposter.com",
  "six-six-six.shoppy.pl", "sizzlemc.com", "sjuaq.com", "skeefmail.com",
  "skfx.cf", "skitz.me", "skrx.tk", "sky-mail.ga",
  "slaskpost.se", "slave-auctions.net", "slipry.com", "slopsmail.com",
  "slothmail.net", "slushmail.com", "slutty.horse", "smaak.testornot.com",
  "smanual.testornot.com", "smallker.tk", "smashmail.de", "smellfear.com",
  "smellybiker.com", "smellybadger.com", "smokingcomputer.com", "sms2email.com",
  "smsemail.xyz", "snakebite.com", "snaknoc.com", "sneakemail.com",
  "sneakmail.de", "snkmail.com", "social-mailer.tk", "sofort-mail.de",
  "sofortmail.de", "softbank.co.jp", "softpls.asia", "sogetthis.com",
  "sohai.ml", "sohus.cn", "solvemail.info", "songwriter.net",
  "sonicemail.com", "sonnenhafen.de", "soodomail.com", "soodonims.com",
  "soon.com", "spam-be-gone.com", "spam-certainly.com", "spam-decoy.net",
  "spam-delivery.com", "spam-free.eu", "spam-free24.com", "spam-goo.com",
  "spam.la", "spam.net", "spam.nomail.net", "spam.org",
  "spam.su", "spam.wtf", "spam4.me", "spamail.de",
  "spamarrest.com", "spamavert.com", "spambob.com", "spambob.net",
  "spambob.org", "spambog.com", "spambog.de", "spambog.net",
  "spambog.ru", "spambo.gq", "spambox.info", "spambox.io",
  "spambox.me", "spambox.org", "spambox.us", "spamcannon.com",
  "spamcannon.net", "spamcero.com", "spamcon.org", "spamcorptastic.com",
  "spamcowboy.com", "spamcowboy.net", "spamcowboy.org", "spamday.com",
  "spamdecoy.net", "spameater.com", "spameater.org", "spamex.com",
  "spamfree24.com", "spamfree24.de", "spamfree24.eu", "spamfree24.info",
  "spamfree24.net", "spamfree24.org", "spamgourmet.com", "spamgourmet.net",
  "spamgourmet.org", "spamherelots.com", "spamhereplease.com", "spamhole.com",
  "spamify.com", "spaminator.de", "spamkill.info", "spaml.com",
  "spamlot.ml", "spamlot.net", "spammail.me", "spammedic.com",
  "spammehere.com", "spammehere.net", "spammer.fail", "spammingemail.com",
  "spammotel.com", "spamobox.com", "spamoff.de", "spamsandwich.com",
  "spamserver.ml", "spamserver.info", "spamserver.net", "spamserver.org",
  "spamslicer.com", "spamsphere.com", "spamspot.com", "spamstack.net",
  "spamthis.co.uk", "spamthis.network", "spamthisplease.com", "spamtrail.com",
  "spamtrap.xyz", "spamtroll.net", "spamwc.de", "spamwc.eu",
  "spamwc.info", "spamwc.net", "spamwc.org", "spamtrap.net",
  "speed.1s.fr", "spikio.com", "spindl-e.com", "spoofmail.de",
  "spr.io", "spritzzone.de", "spybox.de", "squizzy.com",
  "sry.li", "ssoia.com", "stanford.com", "staralwx.online",
  "starry.com", "startell.com", "startfu.com", "startkeys.com",
  "statdvr.com", "stathost.net", "statiix.com", "stealthmail.com",
  "stealthypost.com", "steambot.net", "stexsy.com", "stinkefinger.net",
  "stop-my-spam.cf", "stop-my-spam.com", "stop-my-spam.ga", "stop-my-spam.gq",
  "stop-my-spam.ml", "stop-my-spam.pp.ua", "storendj.nl", "storiqax.com",
  "stpetersandwich.com", "streamfly.biz", "streamfly.link", "strike.tw",
  "striped.net", "stuckmail.com", "stuffmail.de", "suburbanthug.com",
  "suckmyd.com", "sudolife.me", "sudolife.net", "sudomail.biz",
  "sudomail.com", "sudomail.net", "sudoverse.com", "sudoverse.net",
  "sudoweb.net", "sudoworld.com", "sudoworld.net", "suhu.ga",
  "suioe.com", "super-auswahl.de", "supergreatmail.com", "supermail.cf",
  "supermail.ga", "supermail.gq", "supermail.ml", "superplat.xyz",
  "superrito.com", "supersentai.org", "superstachel.de", "surfmail.tk",
  "susa.net", "suxmail.com", "sweetmail.com", "sweetxxx.de",
  "swift10minutemail.com", "swissmail.com", "sylvannet.com", "symphonyresume.com",
  "syosetu.gq", "system-2121.com", "t.odmail.cn", "t24e4p7.com",
  "tabascof.com", "tafmail.com", "tafmail.net", "tafmail.org",
  "tagyourself.com", "talkinator.com", "tapchicuoihoi.com", "taphear.com",
  "tappin.com", "tarkop.xyz", "taskforceusa.net", "tb-on-line.net",
  "tech69.com", "technis.com", "techoloji.net", "techemail.com",
  "techmail.info", "techman.com", "teemg.com", "teleworm.com",
  "teleworm.us", "telli.xyz", "temp-emails.com", "temp-mail.com",
  "temp-mail.de", "temp-mail.info", "temp-mail.life", "temp-mail.org",
  "temp-mail.ru", "tempail.com", "tempalias.com", "tempcloud.info",
  "tempemail.biz", "tempemail.co.za", "tempemail.com", "tempemail.net",
  "tempinbox.com", "tempmail.co", "tempmail.com", "tempmail.de",
  "tempmail.eu", "tempmail.info", "tempmail.io", "tempmail.it",
  "tempmail.net", "tempmail.org", "tempmail.pro", "tempmail.us",
  "tempmail.win", "tempmail.xyz", "tempmailer.com", "tempmails.org",
  "tempomail.fr", "temporarily.com", "temporarioemail.com.br", "temporary-email.com",
  "temporary-email.net", "temporary.xyz", "temporaryemail.net",
  "temporaryemail.us", "temporaryforwarding.com", "temporaryinbox.com",
  "temporarymail.org", "tempot.email", "tempress.net", "tempsky.com",
  "tempthe.net", "tempymail.com", "ternaklele.ga", "test.com",
  "testore.co", "texacowstar.com", "textart.ru", "thankyou2010.com",
  "thatcoconut.com", "the-unknown.net", "thebest4ever.com", "thecloudindex.com",
  "thedarkmaster.net", "theguestbook.net", "theinternetemail.com", "thejunkmail.com",
  "thelightningmail.net", "themailpro.net", "thembones.com.au", "themostemail.com",
  "thenda.net", "thehoneydonor.com", "thepinkberry.com", "theplug.org",
  "thescrappermovie.com", "thetelemail.com", "thetrash.email", "thex.ro",
  "thismail.net", "thnikka.com", "thomaslucero.us", "thrma.com",
  "throam.com", "thrott.com", "throwam.com", "throwaway.email",
  "throwaway.io", "throwaway.xyz", "throwawayemail.com", "throya.com",
  "thrubay.com", "thunderheist.com", "tiapz.com", "tijdelijkmailadres.nl",
  "tilien.com", "timeinbox.com", "timormail.com", "tinoza.org",
  "tinyurl24.com", "tipsb.com", "titanmail.com", "tlc-systems.net",
  "tmail.ws", "tmail.com", "tmailbox.com", "tmmail.net",
  "tmp.ref.ht", "tmpemails.info", "tmpjr.me", "tmpmail.net",
  "tmpmail.org", "toddsbighug.com", "toiea.com", "tokem.co",
  "tokenmail.de", "tonymanso.com", "toomail.biz", "top1mail.ru",
  "top1post.ru", "topatopi.com", "topcoolemail.com", "topformmail.com",
  "topfreeemail.com", "topinrock.cf", "topmail.com", "topmail.org",
  "topofertasdehoy.com", "topranklist.de", "toprumours.com", "tormail.net",
  "tormail.org", "toss.pw", "totalvista.com", "toughlife.org",
  "tpg24.com", "tr2k.xyz", "trainmail.com", "tranceversal.com",
  "trash-2009.com", "trash-mail.at", "trash-mail.cf", "trash-mail.com",
  "trash-mail.de", "trash-mail.ga", "trash-mail.gq", "trash-mail.ml",
  "trash-me.com", "trash2009.com", "trash2010.com", "trash2011.com",
  "trash247.com", "trashbox.eu", "trashdevil.com", "trashdevil.de",
  "trashemail.de", "trashemails.de", "trashinbox.net", "trashmail.at",
  "trashmail.com", "trashmail.de", "trashmail.ga", "trashmail.gq",
  "trashmail.io", "trashmail.me", "trashmail.net", "trashmail.org",
  "trashmail.pw", "trashmail.ws", "trashmailer.com", "trashmails.com",
  "trashymail.com", "trashymail.net", "trb.ovh", "trbvn.com",
  "trbvo.com", "trend-maker.com", "trgovinanaveliko.info", "trialmail.de",
  "trickmail.net", "trillianpro.com", "trixtrux1.ru", "trollproject.com",
  "tropicalbass.info", "trungtamtoeic.com", "tryalert.com", "tryninja.io",
  "turoid.com", "turual.com", "tutoreve.com", "tvchd.com",
  "tverya.com", "twc.com", "twinmail.de", "twkly.ml",
  "two-oaks.com", "tyldd.com", "tynne.com", "uber-mail.com",
  "ubismail.net", "ucupdong.xyz", "uemail99.com", "uggsrock.com",
  "uguuchantele.com", "uhhu.ru", "ujijmail.com", "ukr.net",
  "uk.to", "ultra.fyi", "ultramail.net", "umail.net",
  "umbler.net", "unbekannt.info", "unbounded.tech", "undeva.net",
  "unids.com", "unimark.org", "unit7lahaina.com", "universal.pt",
  "unknown.li", "unmail.ru", "upgcs.xyz", "upliftnow.com",
  "uplipht.com", "uploadnolimit.com", "upozowas.live", "urfunktion.se",
  "urhen.com", "uroid.com", "us.af", "usa.cc",
  "usako.net", "usbc.be", "used-products.com", "usenetmail.xyz",
  "utiket.us", "uu.gl", "uwork4.us", "uyhip.com",
  "vaasfc4.tk", "valemail.net", "valhallafoundation.com", "valudeal.net",
  "vankin.de", "vctel.com", "vda.ro", "vedmail.com",
  "velnet.co.uk", "velnet.com", "velnet.us", "vemomail.win",
  "venompen.com", "verifymyemail.com", "verifymyemail.org", "very1.email",
  "veryrealemail.com", "vfemail.net", "vickop.com", "victime.ninja",
  "victoriantwins.com", "vidchart.com", "viditag.com", "viewcastmedia.com",
  "viewcastmedia.net", "viewcastmedia.org", "vikingsonly.com", "vimail24.com",
  "vinbazar.com", "violin24.xyz", "vipmail.name", "vipmail.pw",
  "vipmail.ru", "vipsohu.com", "viral-ppc.info", "virgiliomail.com",
  "virgilio.it", "visa4you.xyz", "vixlet.com", "vjtimail.com",
  "vkcode.ru", "vmailcloud.com", "vmailing.info", "vmani.com",
  "vmpanda.com", "vmro.cz", "vnedu.me", "voidmail.com",
  "voidmail.net", "voidmail.org", "volcanomail.com", "voltaer.com",
  "vomoto.com", "vorga.org", "votiputox.org", "voxelcore.com",
  "vpn.st", "vps911.net", "vpscloud.info", "vpsfree.cz",
  "vpsorg.club", "vpsorg.pro", "vpsorg.top", "vr5guytf.xyz",
  "vsimcard.com", "vssms.com", "vtxmail.com", "vubby.com",
  "vuiy.pw", "vztc.com", "w3codev.xyz", "w8w.pl",
  "wakingupesther.com", "walala.org",
  "wallm.com", "wannaboom.com", "want2lov.com", "wantplay.site",
  "warau.kr", "warbaloo.com", "wardrabatman.com", "warimail.com",
  "warpmail.net", "warrantymessage.com", "wasa-live.com", "watch-harry-potter.com",
  "watchle.in", "watsonc.com", "wbdet.com", "we.qq.my",
  "wearab.net", "web-contact.net", "web-emailbox.com", "web-mail.pp.ua",
  "web2mailpro.com", "webcontact-france.eu", "webemail.me", "webm4il.info",
  "webmail.com", "webtrip.ch", "webuser.in", "wee.my",
  "wefjo.gq", "weg-werf-email.de", "wegwerf-emails.de", "wegwerfadresse.de",
  "wegwerfemail.com", "wegwerfemail.de", "wegwerfemail.info", "wegwerfemail.net",
  "wegwerfemail.org", "wegwerfemailadresse.com", "wegwerfmail.com", "wegwerfmail.de",
  "wegwerfmail.info", "wegwerfmail.net", "wegwerfmail.org", "wegwerpmail.com",
  "wegwerpmail.net", "welpre.xyz", "wepsimail.com", "wertaret.com",
  "wetrainbayarea.com", "wetrainbayarea.org", "wfgdfhj.tk", "whale-mail.com",
  "wh4f.org", "whaddya.net", "whatiaas.com", "whatifanalytics.com",
  "whatpaas.com", "whatsaas.com", "whiffles.org", "whopy.com",
  "whtjddn.33mail.com", "whyspam.me", "wi.zzz.com.ua", "wickedgame.xyz",
  "wickedspam.com", "widmerrobinsonco.com", "wilemail.com", "willhackforfood.biz",
  "willselfdestruct.com", "wimsg.com", "winemaven.info", "wins.com.br",
  "wiz2.site", "wkzjb.com", "wlqc.com", "wlsz3.com",
  "wmikfc.com", "wmsmail.com", "wn8c38i.com", "wo.cz",
  "wobomail.com", "wokcy.com", "wolfmail.ml", "wolfsmail.ml",
  "wolfsmail.tk", "wollan.info", "wonsabi.com", "woodlandmachinery.com",
  "woolseed.com", "work4u.ovh", "workflowy.cn",
  "worldbreak.com", "wosmail.com", "wowmail.com", "wowway.com",
  "writeme.com", "writeme.net", "wroningaway.xyz",
  "wronghead.com", "ws.gy", "wudet.men", "wuespdj.xyz",
  "wupics.com", "wuzup.net", "wuzupmail.net", "wwjmp.com",
  "wwwnew.eu", "wxnw.net", "x1bks.xyz", "x2eme.com",
  "xagloo.com", "xasamail.com", "xaz.xyz", "xcompress.com",
  "xcpy.com", "xemaps.com", "xemne.com", "xents.com",
  "xertx.xyz", "xing886.uu.gl", "xipcj6.xyz", "xkx.me",
  "xload.me", "xmaily.com", "xn--9kq967o.com", "xn--b6p70c.com",
  "xn--derma-3wa.com", "xn--mgbaai7a8h.com", "xn--mgberp4gwa.com",
  "xoxy.net", "xoxo.nyc", "xperiae5.com", "xrho.com",
  "xvx.us", "xwaretech.com", "xwaretech.info", "xwaretech.net",
  "xww.ro", "xy9ce.tk", "xyzfree.net", "xz3.xyz",
  "xzsok.com", "yabai-oppai.com", "yahmail.top", "yanet.me",
  "yannmail.com", "yapped.net", "yarnp.com", "yaxx.com",
  "ycare.de", "ycnw.net", "ye.vc", "yedi.org",
  "yep.it", "yepmail.net", "yewmail.com", "yhg.biz",
  "ynmrealty.com", "yop.com", "yopmail.com", "yopmail.fr",
  "yopmail.gq", "yopmail.net", "yopmail.org", "yopmail.pp.ua",
  "yordanmail.com", "youdontcare.com", "yougotgoated.com", "youmail.com",
  "youmailr.com", "youneedmore.info", "your-cat.shop", "your-mail.com",
  "yourdomain.com", "youremail.cf", "youremail.ga", "youremail.gq",
  "yourinbox.top", "yourlifedrop.com", "yourname.freeservers.com", "yournightmare.com",
  "yours.com", "yourspam.com", "yourtoken.xyz", "ytrr.xyz",
  "yuurok.com", "yx.dns-cloud.net", "yx.dns-dynamic.net", "yx.dns-mail.com",
  "yx32.com", "z1p.biz", "z86.ru", "zain.site",
  "zainmax.net", "zaktouni.fr", "zarabotokdoma11.ru", "zasod.com",
  "zavio.com", "zaym-zaym.ru", "ze.gally.jp", "zeptu.xyz",
  "zepp.dk", "zetmail.com", "zhcne.com", "zhewei88.com",
  "zhorachu.com", "zik.dj", "zipcad.com", "zipo.xyz",
  "zippymail.info", "zoaxe.com", "zoemail.com", "zoemail.net",
  "zoemail.org", "zombie-hive.com", "zomg.info", "zoro.xyz",
  "zsero.xyz", "zumpat.com", "zvvqkv.xyz", "zxcv.com",
  "zxcvbnm.com", "zzn.com", "zzz.com",
]);

// Pattern-based fallback to catch temp mail domains not in the static list
const DISPOSABLE_PATTERNS = [
  /^(?:.+\.)?tempmail/i,
  /^(?:.+\.)?temp-?mail/i,
  /^(?:.+\.)?trashmail/i,
  /^(?:.+\.)?trash-?mail/i,
  /^(?:.+\.)?throwaway/i,
  /^(?:.+\.)?throw-?away/i,
  /^(?:.+\.)?disposable/i,
  /^(?:.+\.)?fakemail/i,
  /^(?:.+\.)?fake-?mail/i,
  /^(?:.+\.)?spammail/i,
  /^(?:.+\.)?spam-?mail/i,
  /^(?:.+\.)?10minutemail/i,
  /^(?:.+\.)?10minute-?mail/i,
  /^(?:.+\.)?guerrillamail/i,
  /^(?:.+\.)?guerillamail/i,
  /^(?:.+\.)?mailinator/i,
  /^(?:.+\.)?yopmail/i,
  /^(?:.+\.)?maileater/i,
  /^(?:.+\.)?mailexpire/i,
  /^(?:.+\.)?mailmetrash/i,
  /^(?:.+\.)?spambox/i,
  /^(?:.+\.)?jetable/i,
  /^(?:.+\.)?mintemail/i,
  /^(?:.+\.)?tempinbox/i,
  /^(?:.+\.)?discardmail/i,
  /^(?:.+\.)?dispostable/i,
  /^(?:.+\.)?spamgourmet/i,
  /^(?:.+\.)?spamfree/i,
  /^(?:.+\.)?wegwerfmail/i,
  /^(?:.+\.)?wegwerf-?mail/i,
  /^(?:.+\.)?mailnator/i,
  /^(?:.+\.)?mailexpire/i,
  /^(?:.+\.)?mailcatch/i,
  /^(?:.+\.)?maileater/i,
  /^(?:.+\.)?maildrop/i,
  /^(?:.+\.)?guerrilla/i,
  /^(?:.+\.)?sharklasers/i,
  /^(?:.+\.)?spamavert/i,
  /^(?:.+\.)?tempail/i,
  /^mail[0-9]+\./,
  /^temp[0-9]+\./,
  /^trash[0-9]+\./,
  /^spam[0-9]+\./,
];

export function isDisposableEmail(email) {
  if (!email || !email.includes("@")) return false;
  const domain = email.split("@")[1].toLowerCase().trim();

  if (DISPOSABLE_DOMAINS.has(domain)) return true;

  for (const pattern of DISPOSABLE_PATTERNS) {
    if (pattern.test(domain)) return true;
  }

  return false;
}
